//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderToXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string Name { get; set; }
        public string Location { get; set; }
        public string System { get; set; }
        public int Year { get; set; }
        public string Dir { get; set; }
        public int StateID { get; set; }
        public int OrderID { get; set; }
        public string PO { get; set; }
        public string PODate { get; set; }
        public string SystemType { get; set; }
        public Nullable<double> POTotalAmount { get; set; }
        public string SN { get; set; }
        public string Job { get; set; }
        public string Comments { get; set; }
        public string EstimatedShipmentDate { get; set; }
        public Nullable<bool> Install { get; set; }
        public string InstalledBy { get; set; }
        public string InstallDate { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public Nullable<int> OrderPriority { get; set; }
        public Nullable<int> Packages { get; set; }
        public Nullable<int> Parts { get; set; }
        public Nullable<int> PartsNeedToPull { get; set; }
        public Nullable<int> POs { get; set; }
        public Nullable<int> PosOpen { get; set; }
        public string FullName { get; set; }
    }
}
