//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderToXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPackage
    {
        public int OrderID { get; set; }
        public int PackageID { get; set; }
        public string Comments { get; set; }
        public int OrderOackagsID { get; set; }
        public int Qty { get; set; }
        public Nullable<int> SortingID { get; set; }
        public int ParentPackageID { get; set; }
        public bool IsComplited { get; set; }
        public string PDF { get; set; }
        public int PackageStateID { get; set; }
    }
}
