//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderToXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagePart
    {
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> PartID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Note { get; set; }
        public int PackagePartID { get; set; }
        public int SortingID { get; set; }
    
        public virtual Part Part { get; set; }
    }
}
